[tool.poetry]
name = "migro"
version = "0.1.0"
description = ""
authors = ["Dmitry Mukhin <dm@uploadcare.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
